# Generated by Django 2.2.6 on 2019-10-24 09:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('city', models.CharField(max_length=50)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Place')),
            ],
        ),
        migrations.CreateModel(
            name='WifiPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('bssid', models.CharField(blank=True, default='00:00:00:00:00:00', max_length=20, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('connected', models.BooleanField(default=False)),
                ('topologyMode', models.TextField(blank=True, max_length=255, null=True)),
                ('availableWps', models.BooleanField(blank=True, default=False, null=True)),
                ('isVisible', models.BooleanField(blank=True, default=False, null=True)),
                ('frequency', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('speed_test', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('load_test', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('doing', 'Doing'), ('done', 'Done'), ('drop', 'Drop')], default='to_do', max_length=10)),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
