# Generated by Django 2.2.6 on 2019-10-24 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WifiPoint',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
    ]
