# Generated by Django 2.2.6 on 2019-10-24 09:42

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191024_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='label',
            field=models.CharField(choices=[('not_see', 'Not Visible WiFi'), ('low_signal', 'Low Wifi Signal'), ('noise', 'Noisy Channels'), ('lost_traffic', 'Package Lost'), ('other', 'Other'), ('unlabeled', 'No Label')], default='unlabeled', max_length=20, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='place',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='point',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Place', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.FloatField(blank=True, null=True, verbose_name='X position'),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y Position'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='load_test',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Load Tests'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Point', verbose_name='Map Point'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Wifi Points List'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='speed_test',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Speed Test'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('doing', 'Doing'), ('done', 'Done'), ('drop', 'Drop')], default='to_do', max_length=10, verbose_name='Ticker Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.TextField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
