# Generated by Django 2.2.6 on 2019-10-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_ticket_load_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='point',
            new_name='location_point',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='points',
            new_name='wifi_points',
        ),
    ]
