# Generated by Django 2.2.6 on 2019-10-24 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191024_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.TextField(editable=False, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
