# Generated by Django 2.2.6 on 2019-10-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191024_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.TextField(max_length=255, verbose_name='Title'),
        ),
    ]
